# Develop override settings

url: http://localhost:4001

author:
  avatar: "/assets/images/bio-photo.jpg"

analytics:
  provider: false

comments:
  disqus:
    shortname            : "michaelvdnest-dev"

sass:
  style: expanded