name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: helaili/jekyll-action@2.0.5
      with:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
